### ISSUE TITLE
launching server after install

### ISSUE THREAD

**Issue by meldra** [Mydex/lektor-summernote-plugin#1]
Freshly installed/updated debian bullseye with freshly installed lektor installed by various methods; Tried on debian packaged 3.1.3, pipx installed version 3.3.2 and git version 3.3.3.dev9+g9ede53d.d20220320.

If I wrap the final 2 lines of lektor-summernote.py in `if hasattr(dash, "endpoints"):` then the server launches but the plugin doesn't seem functional. I have no idea how lektor works so no idea what's needed to ensure that the endpoints are populated by this point to offer a fix for the plugin.

Am I missing a dependency or something?

I'm trying to use this plugin but when launching the server, it gives this error.

```
(venv) lektor@lektor:~/testproject$ lektor server --host 0.0.0.0
Updating packages in /home/lektor/.cache/lektor/packages/6f30275abc4d7cc9c7495ba402d14762 for project
/home/lektor/lektor/venv/lib/python3.9/site-packages/pip/_internal/commands/install.py:245: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Obtaining file:///home/lektor/testproject/packages/summernote-plugin
Installing collected packages: lektor-summernote
  Running setup.py develop for lektor-summernote
Successfully installed lektor-summernote
/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
 * Project path: /home/lektor/testproject/testproject.lektorproject
 * Output path: /home/lektor/.cache/lektor/builds/99e2ca72ef0fdf8d9590a052b3bbad35
Traceback (most recent call last):
  File "/home/lektor/lektor/venv/bin/lektor", line 8, in <module>
    sys.exit(main())
  File "/home/lektor/lektor/venv/lib/python3.9/site-packages/lektor/cli.py", line 631, in main
    cli.main(args=args, prog_name=name)
  File "/home/lektor/lektor/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/lektor/lektor/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lektor/lektor/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lektor/lektor/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/lektor/lektor/venv/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/lektor/lektor/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/lektor/lektor/venv/lib/python3.9/site-packages/lektor/cli.py", line 344, in server_cmd
    run_server(
  File "/home/lektor/lektor/venv/lib/python3.9/site-packages/lektor/devserver.py", line 131, in run_server
    env.plugin_controller.emit(
  File "/home/lektor/lektor/venv/lib/python3.9/site-packages/lektor/pluginsystem.py", line 169, in emit
    rv[plugin.id] = handler(**kwargs)
  File "/home/lektor/testproject/packages/summernote-plugin/lektor_summernote.py", line 146, in on_server_spawn
    for path, endpoint in dash.endpoints:
AttributeError: module 'lektor.admin.modules.dash' has no attribute 'endpoints'
```

**Comment by mig5** [comment]
Hello @meldra ,

It looks like there was a big refactor of the Lektor admin system in Lektor 3.3.2. This changed some crucial functionality that this plugin depended on - see https://github.com/lektor/lektor/commit/f65fdacfd56fab41523ae4fde3ae8a461f748edd

At the moment, I can't work out how to refactor the plugin to work with the new Lektor. But I did confirm that everything works ok if you install Lektor 3.3.1 (I am also on Debian Bullseye, and ran `pip3 install lektor==3.3.1` and everything worked with this plugin in its original form).

Sorry for the inconvenience - obviously pinning to an older version of Lektor is not ideal. If I work out what needs to change to work with the new admin system, I'll get the plugin updated. If you figure it out, I'll gladly accept a merge request too!

(It's worth noting that the plugin Lektor-SimpleMDE, which we based our Summernote plugin on, has the same problem: https://github.com/sphericalpm/lektor-simplemde)

**Comment by meldra** [comment]
Thank you for your reply. I did find the same problem with the other plugin and sent them the error output in their contact form.

No rush on fixing things, I'm just poking around, no commitment yet :) Thank you for the plugin.
